foreground              #F4E2DA
background              #2C2C33
selection_foreground    #2C2C33
selection_background    #F4E2DA

cursor                  #9A9A9D
cursor_text_color       #2C2C33

# Black
color0  #515158
color8  #A19087

# Red
color1  #262A4B
color9  #262A4B

# Green
color2  #415160
color10 #415160

# Yellow
color3  #746E77
color11 #746E77

# Blue
color4  #7C97AC
color12 #7C97AC

# Magenta
color5  #A09795
color13 #A09795

# Cyan
color6  #DFAD95
color14 #DFAD95

# White
color7  #E7CEC2
color15 #E7CEC2
